export const GRUPOS_WC2026: Record<string, { tla: string; name: string; crest: string }[]> = {
  A: [
    { tla: "MEX", name: "México", crest: "https://crests.football-data.org/769.svg" },
    { tla: "RSA", name: "Sudáfrica", crest: "https://crests.football-data.org/9396.svg" },
    { tla: "KOR", name: "Corea del Sur", crest: "https://crests.football-data.org/772.png" },
    { tla: "CZE", name: "República Checa", crest: "https://crests.football-data.org/798.svg" },
  ],
  B: [
    { tla: "CAN", name: "Canadá", crest: "https://crests.football-data.org/canada.svg" },
    { tla: "BIH", name: "Bosnia y Herzegovina", crest: "https://crests.football-data.org/bosnia.svg" },
    { tla: "QAT", name: "Qatar", crest: "https://crests.football-data.org/8030.svg" },
    { tla: "SUI", name: "Suiza", crest: "https://crests.football-data.org/788.svg" },
  ],
  C: [
    { tla: "BRA", name: "Brasil", crest: "https://crests.football-data.org/764.svg" },
    { tla: "MAR", name: "Marruecos", crest: "https://crests.football-data.org/morocco.svg" },
    { tla: "HAI", name: "Haití", crest: "https://crests.football-data.org/haiti.svg" },
    { tla: "SCO", name: "Escocia", crest: "https://crests.football-data.org/814.svg" },
  ],
  D: [
    { tla: "USA", name: "Estados Unidos", crest: "https://crests.football-data.org/usa.svg" },
    { tla: "PAR", name: "Paraguay", crest: "https://crests.football-data.org/761.svg" },
    { tla: "AUS", name: "Australia", crest: "https://crests.football-data.org/779.svg" },
    { tla: "TUR", name: "Turquía", crest: "https://crests.football-data.org/803.svg" },
  ],
  E: [
    { tla: "GER", name: "Alemania", crest: "https://crests.football-data.org/759.svg" },
    { tla: "CUW", name: "Curazao", crest: "https://crests.football-data.org/curacao.svg" },
    { tla: "CIV", name: "Costa de Marfil", crest: "https://crests.football-data.org/787.svg" },
    { tla: "ECU", name: "Ecuador", crest: "https://crests.football-data.org/791.svg" },
  ],
  F: [
    { tla: "NED", name: "Países Bajos", crest: "https://crests.football-data.org/8601.svg" },
    { tla: "JPN", name: "Japón", crest: "https://crests.football-data.org/766.svg" },
    { tla: "SWE", name: "Suecia", crest: "https://crests.football-data.org/792.svg" },
    { tla: "TUN", name: "Túnez", crest: "https://crests.football-data.org/tunisia.svg" },
  ],
  G: [
    { tla: "BEL", name: "Bélgica", crest: "https://crests.football-data.org/805.svg" },
    { tla: "EGY", name: "Egipto", crest: "https://crests.football-data.org/825.svg" },
    { tla: "IRN", name: "Irán", crest: "https://crests.football-data.org/iran.svg" },
    { tla: "NZL", name: "Nueva Zelanda", crest: "https://crests.football-data.org/783.svg" },
  ],
  H: [
    { tla: "ESP", name: "España", crest: "https://crests.football-data.org/760.svg" },
    { tla: "CPV", name: "Cabo Verde", crest: "https://crests.football-data.org/cape_verde.svg" },
    { tla: "KSA", name: "Arabia Saudita", crest: "https://crests.football-data.org/saudi_arabia.svg" },
    { tla: "URY", name: "Uruguay", crest: "https://crests.football-data.org/758.svg" },
  ],
  I: [
    { tla: "FRA", name: "Francia", crest: "https://crests.football-data.org/773.svg" },
    { tla: "SEN", name: "Senegal", crest: "https://crests.football-data.org/senegal.svg" },
    { tla: "IRQ", name: "Irak", crest: "https://crests.football-data.org/iraq.svg" },
    { tla: "NOR", name: "Noruega", crest: "https://crests.football-data.org/813.svg" },
  ],
  J: [
    { tla: "ARG", name: "Argentina", crest: "https://crests.football-data.org/762.png" },
    { tla: "ALG", name: "Argelia", crest: "https://crests.football-data.org/algeria.svg" },
    { tla: "AUT", name: "Austria", crest: "https://crests.football-data.org/816.svg" },
    { tla: "JOR", name: "Jordania", crest: "https://crests.football-data.org/8049.png" },
  ],
  K: [
    { tla: "POR", name: "Portugal", crest: "https://crests.football-data.org/765.svg" },
    { tla: "COD", name: "R.D. Congo", crest: "https://crests.football-data.org/congo_dr.svg" },
    { tla: "UZB", name: "Uzbekistán", crest: "https://crests.football-data.org/8070.png" },
    { tla: "COL", name: "Colombia", crest: "https://crests.football-data.org/818.svg" },
  ],
  L: [
    { tla: "ENG", name: "Inglaterra", crest: "https://crests.football-data.org/770.svg" },
    { tla: "CRO", name: "Croacia", crest: "https://crests.football-data.org/799.svg" },
    { tla: "GHA", name: "Ghana", crest: "https://crests.football-data.org/ghana.svg" },
    { tla: "PAN", name: "Panamá", crest: "https://crests.football-data.org/panama.svg" },
  ],
};

export const TEAM_NAMES_ES: Record<string, string> = {
  "Mexico": "México",
  "South Africa": "Sudáfrica",
  "South Korea": "Corea del Sur",
  "Korea Republic": "Corea del Sur",
  "Czechia": "República Checa",
  "Canada": "Canadá",
  "Bosnia-Herzegovina": "Bosnia y Herzegovina",
  "Qatar": "Qatar",
  "Switzerland": "Suiza",
  "Brazil": "Brasil",
  "Morocco": "Marruecos",
  "Haiti": "Haití",
  "Scotland": "Escocia",
  "United States": "Estados Unidos",
  "Paraguay": "Paraguay",
  "Australia": "Australia",
  "Turkey": "Turquía",
  "Germany": "Alemania",
  "Curaçao": "Curazao",
  "Ivory Coast": "Costa de Marfil",
  "Ecuador": "Ecuador",
  "Netherlands": "Países Bajos",
  "Japan": "Japón",
  "Sweden": "Suecia",
  "Tunisia": "Túnez",
  "Belgium": "Bélgica",
  "Egypt": "Egipto",
  "Iran": "Irán",
  "New Zealand": "Nueva Zelanda",
  "Spain": "España",
  "Cape Verde Islands": "Cabo Verde",
  "Cape Verde": "Cabo Verde",
  "Saudi Arabia": "Arabia Saudita",
  "Uruguay": "Uruguay",
  "France": "Francia",
  "Senegal": "Senegal",
  "Iraq": "Irak",
  "Norway": "Noruega",
  "Argentina": "Argentina",
  "Algeria": "Argelia",
  "Austria": "Austria",
  "Jordan": "Jordania",
  "Portugal": "Portugal",
  "Congo DR": "R.D. Congo",
  "Uzbekistan": "Uzbekistán",
  "Colombia": "Colombia",
  "England": "Inglaterra",
  "Croatia": "Croacia",
  "Ghana": "Ghana",
  "Panama": "Panamá",
  "USA": "EE.UU.",
  "Bosnia-H.": "Bosnia y Herz.",
};